### ISSUE TITLE
number input not working with min max val 

### ISSUE THREAD

**Issue by BaconianCipher** [jpnurmi/flutter_spinbox#8]
Hi, in case a min val >9 is used one can not input a value anymore after the current one is deleted. To reproduce define a Spinbox like this:
```
SpinBox(
                min:10,
                max: 100.0,
                value: 50.0,
                decimals: 0,
                step: 1,
                decoration: InputDecoration(labelText: 'Decimals'),
              ),
```
select and cut the value so the number field is blank, now try to click on any number on the keyboard. All input seems to be rejected. Most likely because the value is out of bounds. The +- on the other hand still work since it probably produces a start value that is within the tolerated range. 
Regards

**Comment by jpnurmi** [comment]
Thank you! A potential solution could be to make the input validation less strict, and then fixup the value when input focus is lost or the value is submitted.

**Comment by jpnurmi** [comment]
Could you help out to test if the behavior proposed by #8 is correct, please?

```
dependency_overrides:
  flutter_spinbox:
    git:
      url: https://github.com/jpnurmi/flutter_spinbox.git
      ref: validation
```
